# Generated by Django 4.0.4 on 2022-09-06 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CateringApp', '0005_producthistory_delete_product_group_master_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_master',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CateringApp.product_category'),
        ),
    ]
