# Generated by Django 4.0.4 on 2022-09-07 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CateringApp', '0006_product_master_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_master',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderid', models.CharField(blank=True, max_length=100, null=True)),
                ('productid', models.TextField(blank=True, max_length=100, null=True)),
                ('status', models.IntegerField(choices=[(1, 'Dispatch'), (2, 'Shipped'), (3, 'On the way'), (4, 'nearest to location'), (5, 'Delivered'), (6, 'Return'), (7, 'Refund'), (8, 'Exchange')], default=1)),
                ('price', models.CharField(blank=True, max_length=100, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CateringApp.userprofile')),
            ],
        ),
    ]
