# Generated by Django 4.0.4 on 2022-09-16 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CateringApp', '0009_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_master',
            name='detaildesc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
