# Generated by Django 4.0.4 on 2022-09-17 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CateringApp', '0011_alter_cart_productid_alter_cart_quantity_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='ranking',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
