# Generated by Django 4.0.4 on 2022-10-07 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CateringApp', '0014_order_country_order_quantity_order_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(1, 'Dispatch'), (2, 'Shipped'), (3, 'On the way'), (4, 'nearest to location'), (5, 'Delivered'), (6, 'Cancel'), (7, 'Return'), (8, 'Refund'), (9, 'Exchange')], default=1),
        ),
    ]
