# Generated by Django 4.2.2 on 2023-06-26 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CateringApp', '0015_alter_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
                ('userrole', models.CharField(blank=True, max_length=100, null=True)),
                ('created', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='order',
            old_name='country',
            new_name='payment_type',
        ),
        migrations.RemoveField(
            model_name='order',
            name='state',
        ),
        migrations.RemoveField(
            model_name='order',
            name='zipcode',
        ),
        migrations.AddField(
            model_name='order',
            name='pickup_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product_category',
            name='image',
            field=models.FileField(null=True, upload_to='product/'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(1, 'Order Confirmation'), (2, 'Order Processing'), (3, 'Preparing Food'), (4, 'Order Ready'), (5, 'Order Completion'), (6, 'Cancel Order'), (7, 'Refund')], default=1),
        ),
    ]
