# Generated by Django 4.2.2 on 2023-06-26 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CateringApp', '0016_staff_rename_country_order_payment_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='pickup_time',
        ),
    ]
