# Generated by Django 5.1.6 on 2025-04-28 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CateringApp', '0022_alter_productimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producthistory',
            name='productcategoryid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CateringApp.product_category'),
        ),
        migrations.AlterField(
            model_name='producthistory',
            name='productid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CateringApp.product_master'),
        ),
    ]
