# Generated by Django 5.1.6 on 2025-04-28 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CateringApp', '0023_alter_producthistory_productcategoryid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producthistory',
            name='productcategoryid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='producthistory',
            name='productid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
