# Generated by Django 5.1.6 on 2025-04-28 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CateringApp', '0024_alter_producthistory_productcategoryid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producthistory',
            name='productid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CateringApp.product_master'),
        ),
    ]
